{% set name = "types-colorama" %}
{% set version = "0.4.15.20240311" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-colorama-{{ version }}.tar.gz
  sha256: a28e7f98d17d2b14fb9565d32388e419f4108f557a7d939a66319969b2b99c7a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/colorama-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for colorama
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
